project/myapp/urls.py
from . import views
from django.conf.urls import url

app_name = 'myapp' \
           ''
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^student/$', views.studentlogin, name='student'),
    url(r'^teacher/$', views.teacherlogin, name='teacher'),
    url(r'^zhuanjia/$', views.zhuanjialogin, name='zhuanjia'),
    url(r'^danwei/$', views.danweilogin, name='danwei'),
    url(r'^student/register/$', views.studentregister),
    url(r'^student/user/$', views.studentuser, name='studentuser'),
    url(r'^teacher/user/$', views.teacheruser, name='teacheruser'),
    url(r'^zhuanjia/user/$', views.zhuanjiauser, name='zhuanjiauser'),
    url(r'^danwei/user/$', views.danweiuser, name='danweiuser'),
    url(r'^logouts/$', views.logouts, name='logouts'),
    url(r'^logoutt/$', views.logoutt, name='logoutt'),
    url(r'^logoutz/$', views.logoutz, name='logoutz'),
    url(r'^logoutb/$', views.logoutb, name='logoutb'),
    url(r'^student/change1/$', views.studentchange1, name='change1'),
    url(r'^student/change2/$', views.studentchange2, name='change2'),
    url(r'^student/user/(\d+)$', views.studenttostudent, name='studenttostudent'),
    url(r'^student/user/assess/$',views.studentassess, name='assess'),
    url(r'^student/user/selfestimate/$',views.studentselfestimate, name='selfestimate'),
    url(r'^teacher/user/(\d+)/$', views.popwindow, name='popwindow'),
    url(r'^teacher/user/check/$', views.comments_upload, name='comments_upload'),
    url(r'^check/case/$', views.comments_case, name='comments_case'),
    url(r'^zhuanjia/user/(\d+)$', views.zhuanjiatostudent, name='zhuanjiatostudent'),
    url(r'^danwei/user/(\d+)$', views.danweitostudent, name='danweitostudent'),
    url(r'^student/user/student_score/$', views.student_score, name='student_score')

    # url(r'^(?P<title>.+)/$', views.checkwindow, name='checkwindow'),
]

project/myapp/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, JsonResponse
from django.contrib import sessions
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .forms import *
from django.template.defaulttags import register
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from pdfminer.pdfparser import PDFParser,PDFDocument
# from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
# from pdfminer.converter import PDFPageAggregator
# from pdfminer.layout import LAParams, LTTextBoxHorizontal

#增加读取字典的函数
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

# Create your views here.

def ProfessorEvaluate(Professor):
    a = 0
    for professor in Professor:
        a += professor[2] * (professor[1] * professor[1] - professor[0] * professor[0])

    b = 0
    for professor in Professor:
        b += professor[2] * (professor[1] - professor[0])

    Q_ = a/(2 * b)

    a = 0
    for professor in Professor:
        a += (professor[1] - Q_) * (professor[1] - Q_) * (professor[1] - Q_) - (professor[0] - Q_) * (professor[0] - Q_) * (professor[0] - Q_)

    g = a/(3 * b)

    b = 1/(1 + g)
    return (Q_, b)

# def changePdfToText(filePath):
#     # 获取文档对象
#     pdf0 = open(filePath, 'rb')
#
#     # 创建一个与文档关联的解释器
#     parser = PDFParser(pdf0)
#
#     # 创建一个PDF文档对象
#     doc = PDFDocument()
#
#     # 连接两者
#     parser.set_document(doc)
#     doc.set_parser(parser)
#
#     # 文档初始化
#     doc.initialize('')
#
#     # 创建PDF资源管理器
#     resources = PDFResourceManager()
#
#     # 创建参数分析器
#     laparam = LAParams()
#
#     # 创建一个聚合器，并接收资源管理器，参数分析器作为参数
#     device = PDFPageAggregator(resources, laparams=laparam)
#
#     # 创建一个页面解释器
#     interpreter = PDFPageInterpreter(resources, device)
#
#     result = ''
#     # 使用文档对象获取页面的集合
#     for page in doc.get_pages():
#         # 使用页面解释器读取页面
#         interpreter.process_page(page)
#         # 使用聚合器读取页面页面内容
#         layout = device.get_result()
#
#         i = 1
#         for out in layout:
#             if (isinstance(out,LTTextBoxHorizontal)):
#                 if i != 1:
#                     result = result + out.get_text()
#                 i += 1
#
#     pdf0.close()
#     return result
#
# def jiansuo(keyword, host):
#     CONTENT = ['']
#     for line in host:
#         l = ''
#         for key in keyword:
#             splt = line.split(key)
#             if (len(splt) - 1):
#                 string = ''
#                 for item in splt[0: -1]:
#                     string = string + item + "<%s>" % (key)
#                 string = string + splt[-1]
#                 l = line = string
#
#         if len(l):
#             CONTENT.append(l)
#
#     return CONTENT

######################################################

def index(request):
    return render(request, 'myapp/index.html')

def studentlogin(request):
    message = ""
    if request.method == 'POST':
        login_form = IdForm(request.POST)
        message = "输入不合法"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            try:
                user = Postgraduates.objects.get(Pid=username)
                if user.Ppassword == password:
                    request.session['username'] = username
                    request.session.set_expiry(0)
                    return  redirect('user/')
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在"
        return render(request, 'myapp/studentlogin.html', locals())

    login_form = IdForm()
    return render(request, 'myapp/studentlogin.html', locals())

def studentregister(request):
    message = ""
    if request.method == 'POST':
        userform = UserForm(request.POST)
        if userform.is_valid():
            username = userform.cleaned_data['username']
            user = Postgraduates.objects.filter(Pid = username)
            if len(user) != 0:
                message = "用户名已存在"
            else:
                password1 = userform.cleaned_data['password1']
                password2 = userform.cleaned_data['password2']
                if password1 == password2:
                    gender = userform.cleaned_data['gender']
                    if gender == "男" or gender == "女":
                        if gender == "男":
                            gender = True
                        else:
                            gender = False
                        name = userform.cleaned_data['name']
                        grade = userform.cleaned_data['grade']
                        degree = userform.cleaned_data['degree']
                        experience = userform.cleaned_data['experience']
                        user = Postgraduates.objects.create(Pid=username, Pname=name, Ppassword=password2, Pgender=gender, Pgrade=grade, Pdegree=degree, Pexperience=experience)
                        Postgraduates.save(user)
                        return redirect("myapp:studentuser")
                    else:
                        message = "性别必须为男，女"
                else:
                    message = "两次密码输入不同"

        return render(request, 'myapp/studentregister.html', locals())

    else:
        userform = UserForm()
    return render(request, 'myapp/studentregister.html', locals())

def studentuser(request):
    message = ""
    if  request.session.get("username", None):
        username = request.session.get("username")
        user = Postgraduates.objects.get(Pid = username)
        filename = UpFile()
        if request.method == 'POST':
            fileform = UpFile(request.POST)
            if fileform.is_valid():
                FileName = fileform.cleaned_data['UpType']
                if 'submit' in request.POST:
                    if FileName == '上传论文':
                        for file in request.FILES.getlist('test'):
                            empt = PostgraduatesTest()
                            empt.postgraduates = user
                            empt.Ptest = file
                            empt.student_id = str(user.id)
                            empt.name = file.name
                            empt.save()

                    elif FileName == '上传作业':
                        for file in request.FILES.getlist('test'):
                            empt = PostgraduatesHomework()
                            empt.postgraduates = user
                            empt.Phomework = file
                            empt.student_id = str(user.id)
                            empt.name = file.name
                            empt.save()

        try:
            document_test = []
            for i in PostgraduatesTest.objects.filter(student_id=user.id):
                document_test.append(i)
        except:
            document_test = '学生还未提交论文'

        try:
            document_homework = []
            for i in PostgraduatesHomework.objects.filter(student_id=user.id):
                document_homework.append(i)
        except:
            document_homework = '学生还未提交作业'

        page_num = request.GET.get('page', 1)
        student = []
        for i in Postgraduates.objects.filter(Pgrade=user.Pgrade):
            if i.id != user.id:
                student.append(i)

        paginator = Paginator(student, 10)
        paginator_object = paginator.get_page(page_num)
        current_page = paginator_object.number
        page_range = []
        for i in range(max(1, current_page - 2), current_page):
            page_range.append(i)
        for i in range(current_page, min(paginator.num_pages, current_page + 2) + 1):
            page_range.append(i)

        return render(request, 'myapp/studentuser.html', locals())


    else:
        return redirect('myapp:student')

def studentchange1(request):
    if  request.session.get("username", None):
        username = request.session.get("username")
        user = Postgraduates.objects.get(Pid=username)
        if request.method == 'POST':
            userform = ChangeForm(request.POST)
            if userform.is_valid():
                name = userform.cleaned_data['name']
                grade = userform.cleaned_data['grade']
                degree = userform.cleaned_data['degree']
                experience = userform.cleaned_data['experience']
                if userform.cleaned_data['gender']:
                    gender = True
                else:
                    gender = False
                user.Pname = name
                user.Pgrade = grade
                user.Pdegree = degree
                user.Pexperience = experience
                user.Pgender = gender
                user.save()
                return redirect('myapp:studentuser')

        login_form = ChangeForm()
        return render(request, 'myapp/studentchange1.html', locals())
    else:
        return redirect('myapp:student')

def studentchange2(request):
    message = ""
    if  request.session.get("username", None):
        username = request.session.get("username")
        user = Postgraduates.objects.get(Pid=username)
        if request.method == 'POST':
            userform = PasswordForm(request.POST)
            if userform.is_valid():
                password1 = userform.cleaned_data['password1']
                password2 = userform.cleaned_data['password2']
                if password1 == password2:
                    user.Ppassword = password1
                    user.save()
                    return redirect('myapp:student')
                else:
                    message = "两次输入密码不一致"

        login_form = PasswordForm()
        return render(request, 'myapp/studentchange2.html', locals())

    else:
        return redirect('myapp:student')

def studentassess(request):
    message = "无"
    if  request.session.get("username", None):
        username = request.session.get("username")

project/templates/myapp/checkwindow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{key_word}}</h1>

    {% for i in JianSuo %}
        <p>
            <h2>{{i}}</h2>
        </p>
    {% endfor %}
</body>
</html>

project/templates/myapp/studentuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.Pname}}</title>


    {% load staticfiles %}
    <link rel="stylesheet" type="text/css"
          href="{% static '/myapp/css/studentuser.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static '/myapp/css/fenye.css' %}">
    <script src="/static/myapp/js/jquery-3.3.1.min.js"></script>
    <script src="/static/myapp/js/tanchuan.js"></script>
    <script src="/static/myapp/js/daohangtiao.js"></script>
    <script src="/static/myapp/js/time_display.js"></script>
    <script src="/static/myapp/js/upload_document.js"></script>

</head>

<body onLoad="showTime()" class="body">
        <form name="timeform" method="POST" action="">
            <table width="10px" style="position:absolute;top:24px;left:305px;">
                <tr>
                    <td colspan="2">
                    <input name="timearea" type="text" size="30" align="middle" style="background-color:rgb(123,205,254);border:none;font-size:14px;" readonly="readonly"></td>
                </tr>
            </table>
        </form>

            <div><img src="/static/myapp/img/4.png" width="100%" height="250px"></div>
            <div style="position:absolute;top:17px;left:12px"><img src="/static/myapp/img/10.png" ></div>

            <!--<h1 class="header">欢迎{{user.Pname}}</h1>-->


                <a  href="{% url 'myapp:change1' %}" class="menu_head1">更改信息</a>
                <a href="{% url 'myapp:change2' %}" class="menu_head2" >更改密码</a>
                <a href="{% url 'myapp:logouts' %}" class="menu_head3" >注销</a>


<ul class="nav">
 <!--<li><a onclick="applySelectedTo(this);return false;" href="#heartbreakHotel" class="selected">主页</a></li>-->
    <li><a onclick="applySelectedTo(this);return false;" href="#Stu" class="selected">学生互评</a></li>
    <li><a onclick="applySelectedTo(this);return false;" href="#Tev">提交论文和作业</a></li>
    <li><a onclick="applySelectedTo(this);return false;" href="{% url 'myapp:assess' %}">主观指标评价</a></li>
    <li><a onclick="applySelectedTo(this);return false;" href="{% url 'myapp:selfestimate' %}">能力指标自我评价</a></li>
    <li><a onclick="applySelectedTo(this);return false;" href="{% url 'myapp:student_score' %}">学生总分查询</a></li>
</ul>

<div  id="content">
 <!--<div class="on" id="heartbreakHotel">-->
                                <!--<p style="position:absolute;top:250px;left:28%;heoght:50%"><img src="/static/myapp/img/8.jpg" ></p>-->

 <!--</div>-->

 <div class="on" id="Stu" style="position:relative;top:50px;left:600px;width:500px;height:1000px;">
         {% for i in paginator_object.object_list %}
            <p style="position:relative;top:5px;left:100px;width:500px;height:34.5px;">
                <a href="javascript:void(0);" onclick="popupFunc({{i.id}}1)">{{i}}打分</a>
                <a href="javascript:void(0);" onclick="popupFunc({{i.id}}2)">{{i}}总分</a>
            </p>
         {% endfor %}

        <ul class="pagination" style="background-color:rgb(240,255,251);height:auto;width:auto;position:relative;top20px;left:90px;">
            {% if paginator_object.has_previous %}
                <li>
                    <a href="?page={{paginator_object.previous_page_number}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a></li>
            {% else %}
                <li><span aria-hidden="true">&laquo;</span></li>
            {% endif %}

            {% for page_num in page_range %}
                {% if page_num == paginator_object.number %}
                    <li class="active"><span>{{page_num}}</span></li>
                {% else %}
                    <li><a href="?page={{page_num}}">{{page_num}}</a></li>
                {% endif %}

            {% endfor %}

            {% if paginator_object.has_next %}
                <li>
                    <a href="?page={{paginator_object.next_page_number}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li><span aria-hidden="true">&raquo;</span></li>
            {% endif %}


        </ul>
 </div>

 <div id="Tev"  style=";text-align:center;position:fixer;top:80px;">
         <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table align="center" style="position:relative;top:100px;" >
                    <tbody>
                            <tr>
                                <td>{{filename.UpType}}</td>
                                <td><input type="file"  id="up_file1" name="test" onchange="fileChange1(this);" align="center" multiple ></td>
                                <td><input id="submit_upload1" type="submit" class="load-btn" value="上传" name="submit" disabled></td>
                            </tr>
                    </tbody>
                </table>
        </form>

            <table align="center" border="1" style="position:relative;top:100px;">
                <tr>
                    <td>
                        已上交的作业
                    </td>
                    <td>
                        {% if document_homework %}

                            {% for item in document_homework %}
                            <p>{{item.name}}</p>
                            {% endfor %}

                        {% else %}
                            {{'学生还未提交作业'}}

                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>
                        已上交的论文
                    </td>
                    <td>
                        {% if document_test %}

                            {% for item in document_test %}
                            <p>{{item.name}}</p>
                            {% endfor %}

                        {% else %}
                            {{'学生还未提交论文'}}

                        {% endif %}
                    </td>
                </tr>
            </table>

 </div>

<div id ="CaseAnalysis" >

</div>

<div id="test"></div>
</div>

</body>
</html>

project/templates/myapp/teacheruser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{user.Tid}}</title>

  {% load staticfiles %}
    <link rel="stylesheet" type="text/css"
          href="{% static '/myapp/css/teacheruser.css' %}">
    <link rel="stylesheet" type="text/css"
          href="/static/myapp/css/fenye.css">
    <script src="/static/myapp/js/daohangtiao.js"></script>
    <script src="/static/myapp/js/tanchuan.js"></script>
    <script src="/static/myapp/js/time_display.js"></script>
    <script src="/static/myapp/js/jquery-3.3.1.min.js"></script>
    <!--异步刷新-->
    <script>

        $(document).ready(function(){
            $.ajaxSetup({
                 data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
            });
        $('#form1').submit(function(){
                page = 1;
                Load();

                });
        $('#form2').submit(function(){
                Check_case();

                });

            <!--查学生-->
            function Load(){
                var grade = $("select[name=grade]").val();                 //获得form中用户输入的grade 注意这里的id_grade 与你html中的id一致

                $.ajax({
                    type:"POST",
                    data: {grade:grade,page:1},
                    url: "{% url 'myapp:comments_upload' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,
                    dataType: "html",
                    success: function(data){
                        render (data)

                    },
                    error: function(){
                        alert("请输入正确班级数字");
                    }
                });

            }

            <!--查案例-->
            function Check_case(){
                var Case = $("select[name=casename]").val();                 //获得form中用户输入的grade 注意这里的id_grade 与你html中的id一致

                $.ajax({
                    type:"POST",
                    data: {Case:Case},
                    url: "{% url 'myapp:comments_case' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,
                    dataType: "html",
                    success: function(data){
                        go (data)

                    },
                    error: function(){
                        alert("请选择正确案例");
                    }
                });
            }

        });

<!--分页-->
            <!--{# 上一页 #}-->
        function previous(page) {
            page = page-1;
            search(page);
        }
        <!--{# 下一页 #}-->
        function next(page) {
            page = page +1;
            search(page);
        }
        <!--任意一页-->
        function now(page) {
            page = page
            search(page);
        }
        <!--{# 搜索，与按钮点击事件中函数的完全相同 #}-->
        function search(page) {
            var grade = $("select[name=grade]").val();
            $.ajax({
                type:"POST",
                data: {grade:grade,page:page},
                url: "{% url 'myapp:comments_upload' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                cache: false,
                dataType: "html",
                success:function (data) {
                    render(data)
                }
            });
        }


<!--成功后执行渲染-->
            function render(data){
                        var json = eval('('+data+')');
                        var id = "";
                        var str = "";
                        var html = ""
                        if( json != undefined){
                            if( json.length != 0 ){
                                for(var i= 3; i<json.length;i++){    //遍历data数组
                                    var stem = json[i];

                                    str +=  "<tr>"
                                           + "<td align='center'>"+ "<span>"+ stem[1]+"-"+ "</span>" +"</td>";
                                    if(stem[2]){
                                           str += "<td align='center'>"+ "<span>男-"+ "</span>" +"</td>"
                                    }
                                    else{
                                           str += "<td align='center'>"+ "<span>女-"+ "</span>" +"</td>"
                                    }
                                    str += "<td align='center'>"+ "<span>"+ stem[3]+"班-"+ "</span>" +"</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "1)'>" + "查看学生专业培养评价"+ "</a>"+ "</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "2)'>" + "查看学生自我评价"+ "</a>"+ "</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "3)'>" + "查看学生作业情况"+ "</a>"+ "</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "4)'>" + "查看学生论文情况"+ "</a>"+ "</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "5)'>" + "教师评分"+ "</a>"+ "</td>"
                                           + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc("+ stem[0]+ "7)'>" + "学生总分"+ "</a>"+ "</td>"
                                           + "</tr>";

                                    $("#ul1").html(str); //在html页面id=ul1的标签里显示str内容

                                };


                                <!--{# 上一页，下一页 #}-->
                                 html += '<ul class="pagination" style="background-color:rgb(240,255,251);height:auto;width:auto;">';
                                    if (json[0]>1){
                                        html += '<li><a href="javascript:void(0)" class="btn btn-default" onclick="previous(' + json[0] + ')">&laquo;</a></li>';
                                    }
                                    else {
                                        html += '<li><a href="javascript:void(0)" class="btn btn-default disabled">&laquo;</a></li>';
                                    }
                                    for(var i= 0; i<(json[2].length);i++){
                                        if(json[0]==json[2][i]){
                                            html += '<li class="active"><a href="javascript:void(0)" onclick="now(' + json[2][i] + ')">'+ json[2][i] +'</a></li>'
                                        }
                                        else{
                                            html += '<li><a href="javascript:void(0)" onclick="now(' + json[2][i] + ')">'+ json[2][i] +'</a></li>'
                                        }
                                    };

                                    if (json[1]){
                                        html += '<li><a href="javascript:void(0)" class="btn btn-default" onclick="next(' + json[0] + ')">&raquo;</a></li>';
                                    }
                                    else {
                                        html += '<li><a href="javascript:void(0)" class="btn btn-default disabled">&raquo;</a></li>';
                                    }
                                 html += '</ul>';

                                 $("#nav_btn").html(html);
                            }
                            else{
                                str += '没有这个班级';
                                html = ''
                                $("#ul1").html(str);
                                $("#nav_btn").html(html);
                            };
                        };
            }

            function go(data){
                        var json = eval('('+data+')');
                        var str = "";
                        if( json != undefined){

                            str += "<tr>"
                                 + "<td align='center'>"+ "<a href='javascript:void(0)' onclick='popupFunc(" + json[2] + "8)'>案例评价</a>"+ "</td>"
                                 + "</tr>";

                            for(var i=0; i<json[0].length; i++){
                                str += "<tr>"
                                     + "<td align='center'>"+ "<a href='/upload/"+ json[1] +"/"+ json[0][i] +"' target='_blank'>" + json[0][i] + "</a>"+ "</td>"
                                     + "</tr>"
                            };
                        };
                        $("#u22").html(str);
            }

</script>


</head>

<body onLoad="showTime()" class="body">
            <div ><img src="/static/myapp/img/4.png" width="100%" height="250px"></div>

            <div style="position: absolute;top:16px;"><img src="/static/myapp/img/10.png" align="absmiddle" ></div>

        <form name="timeform" method="POST" action="">
            <table width="10px" style="position:absolute;top:24px;left:305px;">
                <tr>
                    <td colspan="2">
                    <input name="timearea" type="text" size="30" align="middle" style="background-color:rgb(123,205,254);border:none;font-size:14px;" readonly="readonly"></td>
                </tr>
            </table>
        </form>


                <a href="{% url 'myapp:logoutt' %}"  class="menu_head">注销</a>
            <!--<div ><img src="/static/myapp/img/4.png" width="100%" height="250px"></div>-->

            <a class="wc">欢迎您: {{user.Tname}}老师</a>



            <!--导航栏-->
        <ul class="nav">
         <!--<li><a onclick="applySelectedTo(this);return false;" href="#heartbreakHotel" class="selected">主页</a></li>-->
            <li><a onclick="applySelectedTo(this);return false;" href="#Tev" class="selected">指标筛选</a></li>
            <li><a onclick="applySelectedTo(this);return false;" href="#Stu" >专硕指标评价</a></li>
            <li><a onclick="applySelectedTo(this);return false;" href="#CaseAnalysis">案例指标评价系统</a></li>
        </ul>
<div  id="content">
 <!--<div class="on" id="heartbreakHotel">-->
                                <!--<p style="position:absolute;top:250px;left:28%;heoght:50%"><img src="/static/myapp/img/8.jpg" ></p>-->

 <!--</div>-->

     <div id="Stu">

            <form method="post" id="form1" name="form1" onsubmit="return false">
                {% csrf_token %}

                <table class="submit">
                    <tr>
                        <td><h4>输入查询班级</h4></td>
                        <td>
                                <select name="grade"><option></option>
                                    {%for k in AllGrade %}
                                        <option>{{k}}</option>
                                    {% endfor %}
                                </select>
                        </td>
                        <td><input type="submit" value="查询" onclick="" id="submit"></td>

                    </tr>
                </table>
            </form>

         <table id="ul1"  style="position:relative;top:100px;left:300px;width:900px;height:35px"></table>

         <nav id="nav_btn" style="position:relative;top:120px;left:700px;width:500px;height:34.5px;"></nav>


     </div>

    <div class="on" id="Tev"  style="text-align:center;position:fixer;top:10px;">
        <p><a href="javascript:void(0);" onclick="popupFunc({{User.id}}6)" >能力指标—集值统计评价筛选</a></p>
         <!--导航条显示计算好的表格和综合评价指标-->
                 <table style="margin:0px auto;" border="1" width="60%" bgcolor="#e9faff" cellpadding="8" align="center">
                    <tbody>
                            <tr align="center">
                                <td>能力指标</td>
                                <td>原始值</td>
                                <td>标准化值</td>
                                <td>判别</td>
                            </tr>
                    </tbody>
                    <tbody>
                        {% for i,j,k,l in jieguo %}
                            <tr align="center">
                                <td>{{i.targetname}}</td>
                                <td>{{j}}</td>
                                <td>{{k}}</td>
                                <td>{{l}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            #可信度
            <h2>{{Accurcy}}</h2>

    </div>

    <div id ="CaseAnalysis">
            <form method="post" id="form2" name="form2" onsubmit="return false">
                {% csrf_token %}

                <table class="submit">
                    <tr>
                        <td><h4>选择查找的案例</h4></td>
                        <td>
                            <select name="casename"><option></option>
                                {%for k in AllCase %}
                                    <option>{{k}}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td><input type="submit" value="查询" onclick="" id="check"></td>
                    </tr>
                </table>
            </form>

        <table id="u22"  style="position:relative;top:100px;left:350px;width:800px;height:35px"></table>
    </div>

</div>

</body>

</html>